src/Entity/EnseigneType.php
<?php

namespace App\Entity;

use App\Repository\EnseigneTypeRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=EnseigneTypeRepository::class)
 */
class EnseigneType
{
   
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\OneToMany(targetEntity="App\Entity\TypeEns")
     * @ORM\ManyToMany(targetEntity="App\Entity\SpecialiteEnseigne")
     */
    private $id_enseigne;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type;

    public function getIdEnseigne(): ?int
    {
        return $this->id_enseigne;
    }

    public function setIdEnseigne(int $id_enseigne): self
    {
        $this->id_enseigne = $id_enseigne;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }
}

src/Entity/UserJoinedEnseigne.php
<?php

namespace App\Entity;

use App\Repository\UserJoinedEnseigneRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=UserJoinedEnseigneRepository::class)
 */
class UserJoinedEnseigne
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @ORM\ManyToMany(targetEntity="App\Entity\ProfilEns")
     */
    private $id_enseigne;

    /**
     * @ORM\Column(type="integer")
     */
    private $id_user;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $profiles = [];

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $droits = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdEnseigne(): ?int
    {
        return $this->id_enseigne;
    }

    public function setIdEnseigne(int $id_enseigne): self
    {
        $this->id_enseigne = $id_enseigne;

        return $this;
    }

    public function getIdUser(): ?int
    {
        return $this->id_user;
    }

    public function setIdUser(int $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getProfiles(): ?array
    {
        return $this->profiles;
    }

    public function setProfiles(?array $profiles): self
    {
        $this->profiles = $profiles;

        return $this;
    }

    public function getDroits(): ?array
    {
        return $this->droits;
    }

    public function setDroits(?array $droits): self
    {
        $this->droits = $droits;

        return $this;
    }
}

src/Controller/EnseigneController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\HttpClient\HttpClientInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use MercurySeries\FlashyBundle\FlashyNotifier;
use App\Repository\UserJoinedEnseigneRepository;
use App\Entity\UserJoinedEnseigne;
use App\Repository\UserRepository;
use App\Repository\EnseigneTypeRepository;
use App\Entity\EnseigneType;

/**
 * @Route("/dashboard/enseigne")
 */ 
class EnseigneController extends AbstractController
{
	private $apiMyEnseigneUrl = 'my_enseignes.php';
	private $apiAllEnseigneAffilierUrl = 'all_enseigne_affilier.php';
	private $apiAffilierEnseigneCommunaute = 'affilier_enseigne_communaute.php';
	private $apiUpdateEnseigne = 'update_enseigne.php';
    private $apiAddEnseigne = 'add_enseigne.php';

    /**
     * @Route("/create", name="create_enseigne", methods={"POST"})
     */
    public function create(Request $request, HttpClientInterface $client, FlashyNotifier $flashy) 
    {
        $user = $this->getUser();
        if (!$user)
        {
            return $this->redirectToRoute('app_login');
        }

        $submittedToken = $request->request->get('_token');
        if ($this->isCsrfTokenValid('create-item'.$user->getId(), $submittedToken)) 
        {
            $nom_enseigne = $request->request->get('nom_enseigne');
            $code_enseigne = $request->request->get('code_enseigne');
            $id_entreprise = $request->request->get('id_entreprise');

            $response = $client->request('POST', $this->getParameter('API_URL').$this->apiAddEnseigne, [
                    'body' => [
                        'nom_enseigne' => $nom_enseigne,
                        'code_enseigne' => $code_enseigne,
                        'id_entreprise' => $user->getId()
                    ]
                ]);

            $content = $response->getContent();
            $content_array = json_decode($content, true);
            $isSuccess = key_exists("server_response", $content_array) ? $content_array['server_response'][0]['status'] : 0;

            if ($isSuccess == 1) {
                    $flashy->success("Création réussie");
                return $this->redirectToRoute('enseigne');
            }
            else
            {
                $flashy->error("Echec de la création");
                return $this->redirectToRoute('enseigne');
            }
        }
        else
        {
            $flashy->error("Formulaire invalide");
            return $this->redirectToRoute('enseigne');
        }

    }

    /**
     * @Route("/", name="enseigne", methods={"GET"})
     */
    public function index(Request $request, HttpClientInterface $client, UserJoinedEnseigneRepository $userJoinedEnseigneRepository, EnseigneTypeRepository $enseignetypeRepo): Response
    {
    	$user = $this->getUser();
    	if (!$user)
    	{
    		return $this->redirectToRoute('app_login');
    	}

        $enseigneType = $enseignetypeRepo->findAll();
    	
    	//Liste des enseignes affilié à InetSCHOOLS
		$responseEnseigneAffilier = $client->request('POST', $this->getParameter('API_URL').$this->apiAllEnseigneAffilierUrl, [
    			'body' => [
    				'id_communaute' => $this->getParameter('ID_COMMUNAUTE')
    			]
    		]);

    		$content = $responseEnseigneAffilier->getContent();
    		$content_array = json_decode($content, true);
    		$AllEnseigneAffiliees= $content_array['server_responses'][0]['founded'] === 0 ? [] : $content_array['server_responses'];


    	//Obtenir la liste des enseignes rejoints par l'utilisateur connecté
		$enseignesJoined = $userJoinedEnseigneRepository->findBy(['id_user' => $user->getId()]);
		$joined = [];
		foreach ($enseignesJoined as $enseigneJoined)
		{
			foreach ($AllEnseigneAffiliees as $enseigneAffiliee) 
			{
				if($enseigneJoined->getIdEnseigne() == $enseigneAffiliee['id_enseigne'])
					array_push($joined, $enseigneJoined->getIdEnseigne());
			}
		}

        $enseigneTypes = $enseignetypeRepo->findAll();


    	if ($user->getType() === $this->getParameter('TYPE_PARTICULIER')) 
    	{
    		
    		return $this->render('enseigne/index.html.twig', [
	            'affiliées' => $AllEnseigneAffiliees,
	            'joined' => $joined,
	            'enseignesJoined' => $enseignesJoined,
	            'position' => 'Enseigne',
	            'chemin' => 'Enseigne',
                'enseigneTypes' => $enseigneTypes
	        ]);
    	}
    	elseif ($user->getType() === $this->getParameter('TYPE_ENTREPRISE')) 
    	{
    		//Liste des enseignes créer par l'entreprise connectée
	    	$responseMyEnseigne = $client->request('POST', $this->getParameter('API_URL').$this->apiMyEnseigneUrl, [
	    			'body' => [
	    				'id_entreprise' => $user->getId()
	    			]
				]);

			$content = $responseMyEnseigne->getContent();
			$content_array = json_decode($content, true);
			$MyEnseignes = $content_array['server_responses'][0]['founded'] === 0 ? [] : $content_array['server_responses'];
    		
    		
    		$affiliées = [];
    		$myEnseignesId = [];
            $enseignesTypes = [];
    		if(!empty($MyEnseignes) and !empty($AllEnseigneAffiliees) )
    		{
	    		foreach ($MyEnseignes as $enseigne) {
	    			array_push($myEnseignesId, $enseigne['id_enseigne']);
	    			foreach ($AllEnseigneAffiliees as $enseigneAffilie) {
	    				if($enseigne['id_enseigne'] == $enseigneAffilie['id_enseigne'])
	    					array_push($affiliées, $enseigne['id_enseigne']) ;
	    			}
                    foreach ($enseigneTypes as $value) {
                        if($value->getIdEnseigne() == $enseigne['id_enseigne'])       
                            $enseignesTypes[$enseigne['id_enseigne']] = $value->getType();        
                    }
	    		}
    		}
    		

    		return $this->render('enseigne/index.html.twig', [
	            'enseignes' => $MyEnseignes,
	            'affiliées' => $affiliées,
	            'enseignesAffiliees' => $AllEnseigneAffiliees,
	            'myEnseignesId' => $myEnseignesId,
	            'enseignesJoined' => $enseignesJoined,
	            'joined' => $joined,
	            'position' => 'Enseigne',
	            'chemin' => 'Enseigne',
                'enseignesTypes' => $enseignesTypes
	        ]);
    	}
        
    }

    /**
     * @Route("/affilier/{id_enseigne}", name="affilier", methods={"GET"})
     */
    public function affilier(Request $request, $id_enseigne, HttpClientInterface $client, FlashyNotifier $flashy)
    {
    	$user = $this->getUser();
    	if (!$user) {
    		return $this->redirectToRoute('app_login');
    	}

    	$response = $client->request('POST', $this->getParameter('API_URL').$this->apiAffilierEnseigneCommunaute, [
    		'body' => [
    			'id_communaute' => $this->getParameter('ID_COMMUNAUTE'),
    			'id_enseigne' => $id_enseigne
    		]
    	]);

    	$content = $response->getContent();
    	$content_array = json_decode($content, true);
    	$isSuccess = $content_array['server_responses'];
    	if($isSuccess == 1)
    	{
    		$message = "Affiliation réussie";
    		
    	}
    	elseif ($isSuccess == 0) 
    	{
    		$message = "Echec de l'Affiliation";
    	}
    	elseif ($isSuccess == -1) 
    	{
    		$message = "Affiliation déjà existante!";
    		
    	}

    	$flashy->success($message);
    	return $this->redirectToRoute('enseigne');
    }

    /**
     * @Route("/rejoindre/{id_enseigne}", name="rejoindre", methods={"GET"})
     */
    public function rejoindre(Request $request, HttpClientInterface $client, FlashyNotifier $flashy, UserJoinedEnseigneRepository $userJoinedEnseigneRepository, $id_enseigne)
    {
    	$user = $this->getUser();
    	if (!$user) {
    		return $this->redirectToRoute('app_login');
    	}
    	$userJoinedEnseigne = new UserJoinedEnseigne();
    	$userJoinedEnseigne->setIdEnseigne($id_enseigne)
    					   ->setIdUser($user->getId());

    	$entityManager = $this->getDoctrine()->getManager();
    	$entityManager->persist($userJoinedEnseigne);
    	$entityManager->flush();

    	$message = "Succès de l'intégration";
    	$flashy->success($message);
    	return $this->redirectToRoute('enseigne');

    }  

    /**
     * @Route("/membres/{id_enseigne}", name="membre", methods={"GET", "POST"})
     */
    public function membres(Request $request, FlashyNotifier $flashy, $id_enseigne, UserJoinedEnseigneRepository $userJoinedEnseigneRepository, UserRepository $userRepository) 
    {
    	$user = $this->getUser();
    	if (!$user) {
    		return $this->redirectToRoute('app_login');
    	}

    	$usersJoined= $userJoinedEnseigneRepository->findBy(['id_enseigne' => $id_enseigne]);
    	$users = $userRepository->findAll();
    	$usersArray = [];

    	foreach ($usersJoined as $userJoined) {
    		foreach ($users as $user) {
    			if($user->getId() == $userJoined->getIdUser())
    			{
    				$usersArray[$user->getId()] = $user;
    			}
    		}
    	}

    	return $this->render('enseigne/membres.html.twig', [
	            'usersArray' => $usersArray,
	            'usersJoined' => $usersJoined,
	            'position' => 'Liste des membres',
	            'chemin' => 'Enseigne  /  Liste des membres',
	        ]);
	}

	/**
	 * @Route("/profile", name="profile", methods={"POST"})
	 */
	public function profiles(Request $request, FlashyNotifier $flashy, UserJoinedEnseigneRepository $userJoinedEnseigneRepository, UserRepository $userRepository) 
	{
		$user = $this->getUser();
    	if (!$user) {
    		return $this->redirectToRoute('app_login');
    	}

    	$submittedToken = $request->request->get('_token');
    	if ($this->isCsrfTokenValid('profiles-item'.$user->getId(), $submittedToken)) 
    	{
    		$id_enseigne = $request->request->get('id_enseigne');
    		$id_user = $request->request->get('id_user');	
    		$profiles = $request->request->get('profiles');

templates/enseigne/membres.html.twig
{% extends 'base.html.twig' %}

{% block title %}KhaMELIA - Enseigne/Membres{% endblock %}
{% block stylesheets %}
	
	<link rel="stylesheet" href="{{ asset('assets/vendor/select2/select2.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/jquery-datatables-bs3/assets/css/datatables.css') }} " />
	<link rel="stylesheet" href="{{ asset('assets/vendor/pnotify/pnotify.custom.css') }} " />
	<link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/css/ui-lightness/jquery-ui-1.10.4.custom.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/select2/select2.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-multiselect/bootstrap-multiselect.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-colorpicker/css/bootstrap-colorpicker.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-timepicker/css/bootstrap-timepicker.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/dropzone/css/basic.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/dropzone/css/dropzone.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/bootstrap-markdown/css/bootstrap-markdown.min.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/summernote/summernote.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/summernote/summernote-bs3.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/codemirror/lib/codemirror.css') }}" />
	<link rel="stylesheet" href="{{ asset('assets/vendor/codemirror/theme/monokai.css') }}" />

{% endblock %}

{% block position %}
	{{ position }}
{% endblock %}

{% block chemin %}
	{{ chemin }}
{% endblock %}

{% block body %}
	<div class="row">
		<div class="col-md-6 col-lg-12 col-xl-6">
			<section class="panel">
				<header class="panel-heading">
					<div class="panel-actions">
						<a href="#" class="fa fa-caret-down"></a>
					</div>
					<h2 class="panel-title">
						Liste des membres
					</h2>
				</header>
				<div class="panel-body">
					<table class="table table-bordered table-striped mb-none" id="datatable-default">
						<thead>
							<tr>
								<th class="center">Nom</th>
								<th class="center">Prénoms</th>
								<th class="center">Email</th>
								<th class="">Profiles</th>
								<th class="center">Roles</th>
								<th class="center">Actions</th>
							</tr>
						</thead>
						<tbody>
							{% for userItem in usersJoined %}
								<tr class="gradeX">
									<td>
										{{ usersArray[userItem.idUser].nom }}
									</td>
									<td>
										{{ usersArray[userItem.idUser].prenom }}
									</td>
									<td>
										{{ usersArray[userItem.idUser].email }}
									</td>
									<td class="pl-md left">
										{% for item in userItem.profiles %}
											{% if item == 'patient' %}
												<li>Patient</li>
											{% elseif item == 'parent' %}
												<li>Parent</li>
											{% elseif item == 'medecin' %}
												<li>Médecin</li>
											{% elseif item == 'gardien' %}
												<li>Gardien</li>
											{% elseif item == 'secretaire' %}
												<li>Secrétaire</li>
											{% elseif item == 'laborantin' %}
												<li>Laborantin</li>
											{% elseif item == 'infirmier' %}
												<li>Infirmier</li>
											{% elseif item == 'assistant' %}
												<li>Assistant</li>
											{% elseif item == 'vendeur' %}
												<li>Vendeur</li>
											{% elseif item == 'delegue_medical' %}
												<li>Délmégué médical</li>
											{% elseif item == 'accueil' %}
												<li>Accueil</li>
											{% elseif item == 'directeur_general' %}
												<li>Directeur général</li>
											{% elseif item == 'fondateur' %}
												<li>Fondateur</li>
											{% endif %}
										{% else %}
											néant
										{% endfor %}
									</td>
									<td class="pl-md left">
										{% for item in userItem.droits %}
											{% if item == 'co_administrateur' %}
												<li>Co adminitrateur</li>
											{% endif %}
										{% else %}
											néant
										{% endfor %}
									</td>
									<td class="center">
										<a href="#modalForm-{{ userItem.id }}" class="modal-with-form btn btn-primary">
											<span class="fa fa-plus"></span>
											Profiles
										</a>
										<div id="modalForm-{{ userItem.id }}" class="modal-block modal-block-primary mfp-hide">
											<section class="panel">
												<header class="panel-heading">
													<h2 class="panel-title">Ajout de profiles</h2>
												</header>
												<div class="panel-body text-center">
													<div class="modal-wrapper">
														<div class="modal-text">
															<form action="{{ path('profile') }}" method="post">
																<input type="hidden" name="_token" value="{{ csrf_token('profiles-item'~ app.user.id) }}"/>
																<input type="hidden" name="id_user" value="{{ userItem.idUser }}">
																<input type="hidden" name="id_enseigne" value="{{ userItem.idEnseigne }}">
																<div class="form-group">
																	<label class="col-md-3 control-label">Profiles</label>
																	<div class="col-md-6">
																		<select class="form-control" multiple="multiple" data-plugin-multiselect data-plugin-options='{ "enableCaseInsensitiveFiltering": true }' id="ms_example6" name="profiles[]" required="required">
																			<optgroup label="PUBLIC">

																				<option value="patient" {% if "patient" in userItem.profiles %} selected="selected" {% endif %}>Patient</option>

																				<option value="parent" {% if "parent" in userItem.profiles %} selected="selected" {% endif %}>Parent/accompagnateur</option>

																				<option value="medecin" {% if "medecin" in userItem.profiles %} selected="selected" {% endif %}>Médecin</option>

																				<option value="laborantin" {% if "laborantin" in userItem.profiles %} selected="selected" {% endif %}>Laborantin</option>

																				<option value="vendeur" {% if "vendeur" in userItem.profiles %} selected="selected" {% endif %}>Vendeur</option>

																				<option value="delegue_medical" {% if "delegue_medical" in userItem.profiles %} selected="selected" {% endif %}>Délégué médical</option>
																			</optgroup>

																			<optgroup label="ADMINISTRATION">
																				<option value="gardien" {% if "gardien" in userItem.profiles %} selected="selected" {% endif %}>Gardien</option>

																				<option value="secretaire" {% if "secretaire" in userItem.profiles %} selected="selected" {% endif %}>Secrétaire</option>

																				<option value="accueil" {% if "accueil" in userItem.profiles %} selected="selected" {% endif %}>Accueil</option>

																				<option value="assistant" {% if "assistant" in userItem.profiles %} selected="selected" {% endif %}>Assistant</option>

																				<option value="infirmier" {% if "infirmier" in userItem.profiles %} selected="selected" {% endif %} >Infirmier</option>

																				<option value="directeur_general" {% if "directeur_general" in userItem.profiles %} selected="selected" {% endif %} >Directeur Général</option>

																				<option value="fondateur" {% if "fondateur" in userItem.profiles %} selected="selected" {% endif %} >Fondateur</option>
																			</optgroup>
																		</select>
																	</div>
																</div>
																<div class="form-group">
																	<input type="submit" class="btn btn-primary" value="Enrégistrer">
																</div>
															
															</form>
														</div>
													</div>
												</div>
												<footer class="panel-footer">
													<div class="row">
														<div class="col-md-12 text-right">
															
															<button class="btn btn-default modal-dismiss">Annuler</button>
														</div>
													</div>
													
												</footer>
											</section>
										</div>
										<a href="#modalFormDroit-{{ userItem.id }}" class="modal-with-form btn btn-dark">
											<span class="fa fa-info"></span>
											Droits
										</a>
										<div id="modalFormDroit-{{ userItem.id }}" class="modal-block modal-block-primary mfp-hide">
											<section class="panel">
												<header class="panel-heading">
													<h2 class="panel-title">Ajout de droit(s)</h2>
												</header>
												<div class="panel-body text-center">
													<div class="modal-wrapper">
														<div class="modal-text">
															<form action="{{ path('droits') }}" method="post">
																<input type="hidden" name="_token" value="{{ csrf_token('droits-item'~ app.user.id) }}"/>
																<input type="hidden" name="id_user" value="{{ userItem.idUser }}">
																<input type="hidden" name="id_enseigne" value="{{ userItem.idEnseigne }}">
																<div class="form-group">
																	<label class="col-md-3 control-label">Droits</label>
																	<div class="col-md-6">
																		<select class="form-control" multiple="multiple" data-plugin-multiselect data-plugin-options='{ "enableCaseInsensitiveFiltering": true }' id="ms_example6" name="droits[]">
																				<option value="co_administrateur" {% if "co_administrateur" in userItem.droits %} selected="selected" {% endif %}>Co-administrateur</option>
																		</select>
																	</div>
																</div>
																<div class="form-group">
																	<input type="submit" class="btn btn-primary" value="Enrégistrer">
																</div>
															</form>
														</div>
													</div>
												</div>
												<footer class="panel-footer">
													<div class="row">
														<div class="col-md-12 text-right">
															<button class="btn btn-default modal-dismiss">Annuler</button>
														</div>
													</div>
													
												</footer>
											</section>
										</div>
									</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			</section>
		</div>
	</div>
{% endblock %}

{% block javascripts %}
	
	<script src="{{ asset('assets/vendor/select2/select2.js') }} "></script>
	<script src="{{ asset('assets/vendor/jquery-datatables/media/js/jquery.dataTables.js') }} "></script>
	<script src="{{ asset('assets/vendor/jquery-datatables/extras/TableTools/js/dataTables.tableTools.min.js') }} "></script>
	<script src="{{ asset('assets/vendor/jquery-datatables-bs3/assets/js/datatables.js') }} "></script>
	<script src="{{ asset('assets/vendor/pnotify/pnotify.custom.js') }}"></script>
	<script src="{{ asset('assets/javascripts/ui-elements/examples.modals.js') }}"></script>
	<script src="{{ asset('assets/javascripts/forms/examples.advanced.form.js') }}" /></script>

	<script src="{{ asset('assets/vendor/jquery-ui/js/jquery-ui-1.10.4.custom.js') }}"></script>
	<script src="{{ asset('assets/vendor/jquery-ui-touch-punch/jquery.ui.touch-punch.js') }}"></script>
	<script src="{{ asset('assets/vendor/select2/select2.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-multiselect/bootstrap-multiselect.js') }}"></script>
	<script src="{{ asset('assets/vendor/jquery-maskedinput/jquery.maskedinput.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-tagsinput/bootstrap-tagsinput.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-colorpicker/js/bootstrap-colorpicker.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-timepicker/js/bootstrap-timepicker.js') }}"></script>
	<script src="{{ asset('assets/vendor/fuelux/js/spinner.js') }}"></script>
	<script src="{{ asset('assets/vendor/dropzone/dropzone.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-markdown/js/markdown.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-markdown/js/to-markdown.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-markdown/js/bootstrap-markdown.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/lib/codemirror.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/addon/selection/active-line.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/addon/edit/matchbrackets.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/mode/javascript/javascript.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/mode/xml/xml.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/mode/htmlmixed/htmlmixed.js') }}"></script>
	<script src="{{ asset('assets/vendor/codemirror/mode/css/css.js') }}"></script>
	<script src="{{ asset('assets/vendor/summernote/summernote.js') }}"></script>
	<script src="{{ asset('assets/vendor/bootstrap-maxlength/bootstrap-maxlength.js') }}"></script>
	<script src="{{ asset('assets/vendor/ios7-switch/ios7-switch.js') }}"></script>
	<script src="{{ asset('assets/javascripts/tables/examples.datatables.default.js') }}"></script>

		
{% endblock %}